# ansible-playbook.yml
---
- name: Install Docker and Deploy Mini Toolchain
  hosts: localhost
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Copy Dockerfile and app.js
      copy:
        src: "{{ item }}"
        dest: /tmp/
      loop:
        - Dockerfile
        - app.js

    - name: Build Docker image
      command: docker build -t mini-toolchain /tmp

    - name: Run container
      command: docker run -d -p 3000:3000 mini-toolchain
